module.exports = {
   NONE: 0,
   USER_EXISTS: 1,
   USER_DNE: 2,
   PASSWORD_INVALID: 3,
   USERNAME_REQUIRED: 4,
   NEW_USERNAME_REQUIRED: 5,
   PASSWORD_REQUIRED: 6,
   NOT_STARTED: 7,
   STILL_STARTING: 8,
   SESSION_ID_ERROR: 9,
   DATABASE_ERROR: 10
}
